spring:
  application:
    name: eurekaserver
  security:
    user:
      name: eurekaserver
      password: eurekaserver

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false