services:
  msproduct:
    build: .
    container_name: msproduct
    depends_on:
      - db
    networks:
      - microservices-network

  db:
    image: postgres:15-alpine
    container_name: postgres-msproduct
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_product
    ports:
      - "5432:5432"
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true

volumes:
  postgres_product_data: