services:
  eurekaserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eurekaserver
    ports:
      - "8761:8761"
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true